name: tic_tac_taupe
description: "My Betclic technical test"
publish_to: 'none' 
version: 0.0.1+1

environment:
  sdk: ^3.9.0

dependencies:
  audioplayers: ^6.5.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  go_router: ^16.3.0
  rive: ^0.14.0-dev.6
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  riverpod_generator: ^3.0.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/rive/
    - assets/audio/
