// Mocks generated by Mockito 5.4.6 from annotations
// in tic_tac_taupe/test/features/game_settings/data/repositories/game_settings_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tic_tac_taupe/core/local_storage/app_local_storage.dart' as _i2;
import 'package:tic_tac_taupe/features/game_settings/data/sources/game_settings_local_data_source.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppLocalStorage_0 extends _i1.SmartFake
    implements _i2.AppLocalStorage {
  _FakeAppLocalStorage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GameSettingsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameSettingsLocalDataSource extends _i1.Mock
    implements _i3.GameSettingsLocalDataSource {
  MockGameSettingsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppLocalStorage get appLocalStorage =>
      (super.noSuchMethod(
            Invocation.getter(#appLocalStorage),
            returnValue: _FakeAppLocalStorage_0(
              this,
              Invocation.getter(#appLocalStorage),
            ),
          )
          as _i2.AppLocalStorage);

  @override
  _i4.Future<void> saveSettings(String? settingsJson) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [settingsJson]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> fetchSettings() =>
      (super.noSuchMethod(
            Invocation.method(#fetchSettings, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}
