// Mocks generated by Mockito 5.4.6 from annotations
// in tic_tac_taupe/test/features/game/data/repositories/tic_tac_toe_game_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tic_tac_taupe/features/game/data/sources/tic_tac_toe_bot_ai.dart'
    as _i2;
import 'package:tic_tac_taupe/features/game/domain/models/tic_tac_toe_board.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TicTacToeBotAi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTicTacToeBotAi extends _i1.Mock implements _i2.TicTacToeBotAi {
  MockTicTacToeBotAi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> getNextCellMove(_i4.TicTacToeBoard? board) =>
      (super.noSuchMethod(
            Invocation.method(#getNextCellMove, [board]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
